# Generated by Django 4.0.5 on 2022-10-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_editora_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
